### PR TITLE
add supplied_by_domains back to product in order to access the relati…

### PR DESCRIPTION
**Pull request by Amtron**
…onship

Without this I'm unable to access the supplied by domains on the product.

### CODE REVIEW

**Comment by Amtron** [comment]
It works this way, I'm actively using this change in my local because I'm unable to access  supply domains on the product without it.

**Comment by Amtron** [comment]
This isn't my area, so who needs to be assigned to fix this bug?

**Comment by DanielCollins** [comment]
anyone can be assigned. what's needed is a test case or good instructions to reproduce the problem.

**Comment by Amtron** [comment]
@DanielCollins can you please take care of this.

1) login as Fred
2) navigate to Black print tyvek wristbands - http://dev.localhost:4000/products/1/
3) click on the production tab - then the Reseller products - then search a
a bunch or products should display
4) assign a supply product
5) click on the Assigned tab (on the right-hand side)
You should notice that the supply product is shown in the list of assigned
6) refresh the page
You'll notice that the supply product has now gone however, if you check the db you'll be able to find that the relationship exists.

This is due to the python sdk. I've shown this to @s3341458 and he also agrees with me on this.

**Comment by DanielCollins** [comment]
fixed in 4467447

**Comment by Amtron** [comment]
@DanielCollins thanks

**Pull request closed without merging**
