### PR TITLE
add component version to python, javascript and typescript

### PR DESCRIPTION
**Pull request by Amtron**

### CODE REVIEW

**Review by s3341458 — COMMENTED** [review]
Sweep: change 'createdAt' to 'created' and 'created_at' to 'created'

**Comment by s3341458** [comment]
Sweep: change 'createdAt' to 'created' and 'created_at' to 'created'

**Comment by s3341458** [comment]
Sweep: add boolean variable is_class_based to python component_version model and isClassBased to ts and js component_version model. add string variable description to component_version python, js and ts models

**Review by Unitix — APPROVED** [review]
LGTM

**Pull request merged**
