### PR TITLE
Add new tags to templates

### PR DESCRIPTION
**Pull request by Amtron**
@DanielCollins this PR is to help with a new component which is for uploading job files vila public templates.

### CODE REVIEW

**Comment by DanielCollins** [comment]
Adding `a` and `href`  (without further checks) breaks security, i think. Template authors are untrusted. With these tags they can:

- link to phishing or otherwise malicious sites
- run arbitrary javascript and thereby break everything else, too.

**Comment by Amtron** [comment]
> Adding a and href (without further checks) breaks security, i think. Template authors are untrusted. With these tags they can:
 That's right I forgot about this. 

We need 'a' and 'href' for bootstrap tabs. Can you think of a way we can allow 'a' and 'href' or maybe a substitute? We only need the href to link to element ids on the page (href='#element-id'); we don't need the href to link to a URL.

**Comment by DanielCollins** [comment]
i think the whole entire idea of the double template system with two different languages (react and html) kept seperate was that dynamic stuff go into "components" rather than "templates".

but, it should also be possible to add more checks to the template checker to detect a safe subset of urls which should be allowed. at first glance, ones starting with `#` should be safe.

**Comment by Amtron** [comment]
The 'a' element is safe on it's own right?

**Comment by DanielCollins** [comment]
yes

**Pull request closed without merging**
